import Link from "next/link";

/**
 * Caregiver brand mark — vertical teal gradient tile with a white heart
 * cradled in cupped hands. Every element is mirror-symmetric about x=32,
 * matching the favicon/icon set generated by .tmpsecrets/gen-icons.mjs.
 * Single source of truth for the logo (header, footers, auth screens).
 */
export function LogoMark({ size = 36, className = "" }: { size?: number; className?: string }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 64 64"
      className={className}
      role="img"
      aria-label="Caregiver logo"
    >
      <defs>
        <linearGradient id="cg-brand" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#2dd4bf" />
          <stop offset="0.55" stopColor="#0d9488" />
          <stop offset="1" stopColor="#0a5c56" />
        </linearGradient>
        <radialGradient id="cg-glow" cx="0.5" cy="0.38" r="0.62">
          <stop offset="0" stopColor="#ffffff" stopOpacity="0.3" />
          <stop offset="0.6" stopColor="#ffffff" stopOpacity="0.07" />
          <stop offset="1" stopColor="#ffffff" stopOpacity="0" />
        </radialGradient>
      </defs>
      <rect width="64" height="64" rx="16" fill="url(#cg-brand)" />
      <rect width="64" height="64" rx="16" fill="url(#cg-glow)" />
      <g transform="translate(32 32) scale(0.86) translate(-32 -32)">
        <g transform="translate(0 -1.5)">
          <path
            d="M32 40.8 C25.4 35.9 20.5 31.9 20.5 27.2 C20.5 23.6 23.4 21 26.8 21 C29.2 21 31 22.3 32 24 C33 22.3 34.8 21 37.2 21 C40.6 21 43.5 23.6 43.5 27.2 C43.5 31.9 38.6 35.9 32 40.8 Z"
            fill="#ffffff"
          />
          <path
            d="M17.2 31.6 C17.2 41.9 23.8 47.6 32 47.6 C40.2 47.6 46.8 41.9 46.8 31.6"
            fill="none"
            stroke="#ffffff"
            strokeWidth="5.5"
            strokeLinecap="round"
          />
        </g>
      </g>
    </svg>
  );
}

/** Logo lockup — mark + wordmark, links home by default. */
export function Logo({
  href = "/",
  size = 36,
  wordClass = "text-xl font-extrabold tracking-tight text-ink",
  className = "",
}: {
  href?: string;
  size?: number;
  wordClass?: string;
  className?: string;
}) {
  return (
    <Link href={href} className={`flex shrink-0 items-center gap-2.5 ${className}`}>
      <LogoMark size={size} />
      <span className={wordClass}>Caregiver</span>
    </Link>
  );
}
